<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
/** @var array $packages */
// This template is require'd inside Plugin::render_import_page(), so every
// variable here is method-local, not global. The prefix sniff can't see that
// when it scans the file in isolation, so silence its false positives file-wide.
// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound
?>
<div class="wrap sd-wrap">
	<h1><?php esc_html_e( 'Site Cloner – Import (Staging)', 'site-cloner' ); ?></h1>

	<div class="notice notice-warning"><p>
		<strong><?php esc_html_e( 'Warning:', 'site-cloner' ); ?></strong> <?php esc_html_e( 'this operation will', 'site-cloner' ); ?> <strong><?php esc_html_e( 'overwrite all files + the database', 'site-cloner' ); ?></strong> <?php esc_html_e( 'of this staging site.', 'site-cloner' ); ?>
		<?php esc_html_e( "You may be logged out once it's done (because the users table now holds production's data) — log back in using a production account.", 'site-cloner' ); ?>
	</p></div>

	<?php \Flexa\SiteCloner\Health::render(); ?>

	<div class="sd-card sd-pull-card">
		<h2 style="margin-top:0;">⚡ <?php esc_html_e( 'Pull from production via link', 'site-cloner' ); ?></h2>
		<p class="description"><?php esc_html_e( 'Paste the link generated by the', 'site-cloner' ); ?> <em>Tools → Site Cloner</em> <?php esc_html_e( 'page on production. Staging will download the package and migrate automatically — no manual upload needed.', 'site-cloner' ); ?></p>
		<div class="sd-pull-row">
			<input type="text" id="sd-pull-input" placeholder="https://production.com/?sd_pull=...&key=...">
			<button type="button" id="sd-pull-test" class="button" disabled><?php esc_html_e( 'Test connection', 'site-cloner' ); ?></button>
		</div>
		<div id="sd-pull-testresult" class="sd-testresult" style="display:none;"></div>
		<div class="sd-pull-row" style="margin-top:8px;">
			<input type="password" id="sd-pull-password" placeholder="<?php esc_attr_e( 'Password (if the package has one)', 'site-cloner' ); ?>" autocomplete="off">
		</div>
		<p style="margin-top:10px;">
			<label><input type="checkbox" id="sd-pull-insecure"> <?php esc_html_e( 'Skip SSL verification (only for local/self-signed production:', 'site-cloner' ); ?> <code>.test</code>, <code>.local</code>…)</label>
		</p>
		<p style="margin-top:6px;">
			<label><input type="checkbox" id="sd-pull-confirm"> <?php esc_html_e( 'I understand staging will be completely overwritten.', 'site-cloner' ); ?></label>
		</p>
		<button id="sd-pull-start" class="button button-primary button-hero" disabled><?php esc_html_e( 'Pull &amp; Migrate', 'site-cloner' ); ?></button>
	</div>

	<div class="sd-card">
		<h2 style="margin-top:0;"><?php esc_html_e( 'Or select a package already on staging', 'site-cloner' ); ?></h2>
		<p class="description"><?php esc_html_e( 'Copy the package folder into', 'site-cloner' ); ?> <code>wp-content/uploads/sd-packages/</code> <?php esc_html_e( '(via FTP/File Manager), then reload this page.', 'site-cloner' ); ?></p>
		<?php if ( empty( $packages ) ) : ?>
			<p><?php esc_html_e( 'No packages found in', 'site-cloner' ); ?> <code>wp-content/uploads/sd-packages/</code>.</p>
		<?php else : ?>
			<table class="widefat striped" id="sd-pkg-table">
				<thead><tr><th></th><th><?php esc_html_e( 'Package', 'site-cloner' ); ?></th><th><?php esc_html_e( 'Source site', 'site-cloner' ); ?></th><th><?php esc_html_e( 'Created', 'site-cloner' ); ?></th><th><?php esc_html_e( 'Size', 'site-cloner' ); ?></th></tr></thead>
				<tbody>
				<?php foreach ( $packages as $sd_p ) : ?>
					<tr>
						<td><input type="radio" name="sd_pkg" value="<?php echo esc_attr( $sd_p['id'] ); ?>"></td>
						<td><code><?php echo esc_html( $sd_p['id'] ); ?></code></td>
						<td><?php echo esc_html( $sd_p['site_url'] ); ?></td>
						<td><?php echo esc_html( $sd_p['created'] ); ?></td>
						<td><?php echo esc_html( $sd_p['size'] ); ?></td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<p style="margin-top:16px;">
				<label><input type="checkbox" id="sd-confirm"> <?php esc_html_e( 'I understand staging will be completely overwritten.', 'site-cloner' ); ?></label>
			</p>
			<button id="sd-run-import" class="button button-primary button-hero" disabled><?php esc_html_e( 'Run Migrate', 'site-cloner' ); ?></button>
		<?php endif; ?>
	</div>

	<div class="sd-card" id="sd-imp-panel" style="display:none;">
		<div id="sd-imp-progress" class="sd-progress">
			<div class="sd-step" data-step="download" style="display:none;">
				<span class="sd-label"><?php esc_html_e( 'Downloading package from production', 'site-cloner' ); ?></span>
				<div class="sd-bar"><i style="width:0%"></i></div>
			</div>
			<div class="sd-step" data-step="extract">
				<span class="sd-label"><?php esc_html_e( 'Extracting files', 'site-cloner' ); ?></span>
				<div class="sd-bar"><i style="width:0%"></i></div>
			</div>
			<div class="sd-step" data-step="db">
				<span class="sd-label"><?php esc_html_e( 'Import database + search-replace', 'site-cloner' ); ?></span>
				<div class="sd-bar"><i style="width:0%"></i></div>
			</div>
			<p class="sd-status">…</p>
		</div>

		<div id="sd-imp-result" class="sd-result" style="display:none;">
			<h2>✅ <?php esc_html_e( 'Migration complete', 'site-cloner' ); ?></h2>
			<p class="sd-imp-log"></p>
			<p><a class="sd-imp-login" href="#">→ <?php esc_html_e( 'Open wp-admin (log back in if needed)', 'site-cloner' ); ?></a></p>
			<p id="sd-src-uninstall-wrap" style="display:none;margin-top:10px;">
				<button id="sd-src-uninstall" class="button"><?php esc_html_e( 'Remove plugin from the source site', 'site-cloner' ); ?></button>
				<span class="sd-src-uninstall-msg" style="margin-left:8px;"></span>
			</p>
		</div>

		<div id="sd-imp-error" class="notice notice-error" style="display:none;"><p></p></div>
	</div>
</div>
